name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
      - name: install zephyr host dependencies
        run: |
          sudo apt-get install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file libpython3.8-dev \
          make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
      - name: install zephyr arm sdk
        run: |
          cd /opt
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_linux-x86_64_minimal.tar.xz
          wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/sha256.sum | shasum --check --ignore-missing
          tar xvf zephyr-sdk-0.16.3_linux-x86_64_minimal.tar.xz
          cd zephyr-sdk-0.16.3
          ./setup.sh -t arm-zephyr-eabi
      - name: install west
        run: pip install west
      - name: initialize west workspace
        run: west init -l ${{ github.event.repository.name }}
      - name: west update
        run: west update
      - name: build for otterpill board
        run: west build -b otterpill ${{ github.event.repository.name }}
